# Generated by Django 4.1.4 on 2023-01-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_main_image_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='author_email',
        ),
    ]
