# Generated by Django 4.1.4 on 2023-01-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='content',
            field=models.TextField(max_length=1024, null=True, verbose_name='content'),
        ),
    ]
