# Generated by Django 4.1.4 on 2023-01-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productcomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='author_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='author name'),
        ),
    ]
