# Generated by Django 4.1.4 on 2023-01-07 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_productcomment_author_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=128, null=True, verbose_name='fullname')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('delivery', models.CharField(choices=[('reg', 'Regular'), ('exp', 'Express')], default='reg', max_length=3, verbose_name='delivery')),
                ('payment_method', models.CharField(choices=[('card', 'Bank Card'), ('cash', 'From random account')], default='card', max_length=4, verbose_name='payment method')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='city')),
                ('address', models.TextField(blank=True, max_length=256, null=True, verbose_name='address')),
                ('in_order', models.BooleanField(default=False, verbose_name='in order')),
                ('paid', models.BooleanField(default=False, verbose_name='order is payed')),
                ('payment_error', models.CharField(blank=True, max_length=50, null=True, verbose_name='payment error')),
                ('ordered', models.DateTimeField(blank=True, null=True, verbose_name='order placement date')),
                ('braintree_id', models.CharField(blank=True, max_length=150, verbose_name='transaction id')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='delivery cost')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price')),
                ('quantity', models.IntegerField(default=1, null=True, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='products.product')),
            ],
            options={
                'verbose_name': 'order product',
                'verbose_name_plural': 'order products',
            },
        ),
    ]
